## dim of array

In [15]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## array indexing

In [17]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])


2nd element on 1st dim:  2


In [18]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


## Slicing arrays

In [19]:
# import numpy as import numpy as np
# arange() is an inbuilt numpy function that returns an ndarray object containing evenly spaced values within a defined interval
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# with start and stop
print(arr[1:5])

[2 3 4 5]
[2 3 4 5]


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# without stop
print(arr[4:])

[5 6 7]


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# without start
print(arr[:4])

[1 2 3 4]


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# with start, stop,and step
print(arr[1:5:2])

[2 4]


In [23]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# to print the elements from 2nd row,
print(arr[1, 1:4])

[7 8 9]


In [83]:
# LogSpace returns even spaced numbers on a log scale. Logspace has the same parameters as np.linspace.

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("the array is:\n",arr)
lg=np.logspace(1, 4, 1)
print("the log space ary is:\n",lg)

the array is:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
the log space ary is:
 [10.]


In [84]:
import numpy as np  
arr = np.logspace(10, 20, num = 5, endpoint = True)  
print("The array over the given range is ",arr)  

The array over the given range is  [1.00000000e+10 3.16227766e+12 1.00000000e+15 3.16227766e+17
 1.00000000e+20]


In [25]:
import numpy as np
np.linspace(1.0, 5.0, num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

## NumPy Data Types

###### change the data type

In [78]:
# change the dtype to 'float64'
arr = arr.astype('float64')

# Print the array after changing
# the data type
print(arr)

# Also print the data type
print(arr.dtype)

tr=arr.T
print(tr)


[1. 3. 5. 7.]
float64
[1. 3. 5. 7.]


In [27]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [28]:
# change the dtype to 'complex128'
arr = np.array([1,2,7,4])
arr = arr = arr.astype('complex128')

# Print the array after changing
# the data type
print(arr)

# Also print the data type
print(arr.dtype)


[1.+0.j 2.+0.j 7.+0.j 4.+0.j]
complex128


In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [32]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


#### array shaping

In [33]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [35]:
import numpy as np
arr = np.array([[1,3,2,4],[9,4,1,0],[9,5,2,99],[5,3,1,3],[3,7,5,2]])
arr.shape

(5, 4)

##### reshape

In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("the one dimensional array is:",arr)
newarr = arr.reshape(4, 3)

print("the reshaped-4dim array is:",newarr)

the one dimensional array is: [ 1  2  3  4  5  6  7  8  9 10 11 12]
the reshaped-4dim array is: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [81]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# 3 dim array
newarr = arr.reshape(2, 3, 2)
print("the new ary is:\n",newarr)

newarr_t = newarr.T
print("the transpose is:\n",newarr.T)

the new ary is:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
the transpose is:
 [[[ 1  7]
  [ 3  9]
  [ 5 11]]

 [[ 2  8]
  [ 4 10]
  [ 6 12]]]


In [38]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


##### sum

In [16]:
import numpy as np

Q=np.array([[52,52,88,67,39,74],[37,58,12,87,49,75]])
print("the array-Q is:\n",Q)

add=Q.sum(axis=0)
# axis=1-->add all rows nd col separately
# axis=0--->adds all the row with col,separately
print("the sum of Q elements is:\n",add)


# std 
print ("the std is:\n",Q.var(axis=0))
print ("the std is:\n",Q.var(axis=1))

# var
print("the variance is:\n",Q.var(axis=0))
print("the variance is:\n",Q.var(axis=1))

print("the aliter\n",np.var(Q,axis=1))

the array-Q is:
 [[52 52 88 67 39 74]
 [37 58 12 87 49 75]]
the sum of Q elements is:
 [ 89 110 100 154  88 149]
the std is:
 [5.625e+01 9.000e+00 1.444e+03 1.000e+02 2.500e+01 2.500e-01]
the std is:
 [262.33333333 603.        ]
the variance is:
 [5.625e+01 9.000e+00 1.444e+03 1.000e+02 2.500e+01 2.500e-01]
the variance is:
 [262.33333333 603.        ]
the aliter
 [262.33333333 603.        ]


### iterating

In [39]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [40]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [41]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


#### eye method

In [42]:
# numpy.eye method

import numpy as array

# 2x2 matrix with 1's on main diagnol
b = array.eye(2, dtype = float)
print("Matrix b : \n", b)

# matrix with R=4 C=5 and 1 on diagnol
# below main diagnol
a = array.eye(4, 5, k = -1)
print("\nMatrix a : \n", a)


Matrix b : 
 [[1. 0.]
 [0. 1.]]

Matrix a : 
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


##### gaussian array

In [43]:
# Importing Numpy package
import numpy as np

# Initializing value of x-axis and y-axis
# in the range -1 to 1
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
dst = np.sqrt(x*x+y*y)

# Intializing sigma and muu
sigma = 1
muu = 0.000

# Calculating Gaussian array
gauss = np.exp(-( (dst-muu)**2 / ( 2.0 * sigma**2 ) ) )

print("2D Gaussian array :\n")
print(gauss)


2D Gaussian array :

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73

In [44]:
# Importing Numpy package
import numpy as np

# Initializing value of x-axis and y-axis
# in the range -2 to +2
x, y = np.meshgrid(np.linspace(-2,2,15), np.linspace(-2,2,15))
dst = np.sqrt(x*x+y*y)

# Intializing sigma and muu
sigma = 1
muu = 0.000

# Calculating Gaussian array
gauss = np.exp(-( (dst-muu)**2 / ( 2.0 * sigma**2 ) ) )

print("2D Gaussian array :\n")
print(gauss)


2D Gaussian array :

[[0.01831564 0.03113609 0.0487813  0.07043526 0.09372907 0.11494916
  0.12992261 0.13533528 0.12992261 0.11494916 0.09372907 0.07043526
  0.0487813  0.03113609 0.01831564]
 [0.03113609 0.0529305  0.08292689 0.11973803 0.15933686 0.19541045
  0.2208649  0.2300663  0.2208649  0.19541045 0.15933686 0.11973803
  0.08292689 0.0529305  0.03113609]
 [0.0487813  0.08292689 0.12992261 0.1875951  0.24963508 0.30615203
  0.34603184 0.36044779 0.34603184 0.30615203 0.24963508 0.1875951
  0.12992261 0.08292689 0.0487813 ]
 [0.07043526 0.11973803 0.1875951  0.27086833 0.36044779 0.44205254
  0.49963495 0.52045012 0.49963495 0.44205254 0.36044779 0.27086833
  0.1875951  0.11973803 0.07043526]
 [0.09372907 0.15933686 0.24963508 0.36044779 0.47965227 0.58824471
  0.66487032 0.69256932 0.66487032 0.58824471 0.47965227 0.36044779
  0.24963508 0.15933686 0.09372907]
 [0.11494916 0.19541045 0.30615203 0.44205254 0.58824471 0.72142229
  0.81539581 0.84936582 0.81539581 0.72142229 0.5882

##### empty and full array

In [82]:
# python program to create
# Empty and Full Numpy arrays

import numpy as np


# Create an empty array
empa = np.empty((3, 4), dtype=int)
print("Empty Array")
print(empa)

emp_tp=empa.T
print("transpose is:\n",emp_tp)

# Create a full array
flla = np.full([3, 3], 55, dtype=int)
print("\n Full Array")
print(flla)


Empty Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
transpose is:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

 Full Array
[[55 55 55]
 [55 55 55]
 [55 55 55]]


In [46]:
# python program to create
# Empty and Full Numpy arrays

import numpy as np


# Create an empty array
empa = np.empty([4, 2])
print("Empty Array")
print(empa)

# Create a full array
flla = np.full([4, 3], 95)
print("\n Full Array")
print(flla)


Empty Array
[[1. 0.]
 [2. 0.]
 [7. 0.]
 [4. 0.]]

 Full Array
[[95 95 95]
 [95 95 95]
 [95 95 95]
 [95 95 95]]


##### record()

In [47]:
# import numpy
import numpy as np

# using numpy.core.fromrecords() method
gfg = np.core.records.fromrecords([(101, 'Jitender', 21),
									(102, 'Deepak', 20)],
							names = 'Rollno, Name, Age')

print(gfg.Name)


['Jitender' 'Deepak']


In [48]:
# import numpy
import numpy as np

# using numpy.core.fromrecords() method
gfg = np.core.records.fromrecords([(101, 'Jitender', 21),
									(102, 'Deepak', 20)],
							names = 'Rollno, Name, Age')

print(gfg[0])


(101, 'Jitender', 21)


### Array Manipulation

###### copy array from another array

In [49]:
# importing Numpy package
import numpy as np

# Creating a numpy array using np.array()
ary = np.array([13, 99, 100, 34, 65, 11,
				66, 81, 632, 44])

print("Original array: ")

# printing the Numpy array
print(ary)

# Creating an empty Numpy array similar
# to ary
copy = np.empty_like(ary)

# Now assign ary to copy
copy[:] = ary

print("\nCopy of the given array: ")

# printing the copied array
print(copy)


Original array: 
[ 13  99 100  34  65  11  66  81 632  44]

Copy of the given array: 
[ 13  99 100  34  65  11  66  81 632  44]


In [50]:
# importing Numpy package
import numpy as np

# Creating a 3-D numpy array using np.array()
org_array = np.array([[23, 46, 85],
					[43, 56, 99],
					[11, 34, 55]])

print("Original array: ")

# printing the Numpy array
print(org_array)

# Now copying the org_array to copy_array
# using np.copy() function
copy_array = np.copy(org_array)

print("\nCopied array: ")

# printing the copied Numpy array
print(copy_array)


Original array: 
[[23 46 85]
 [43 56 99]
 [11 34 55]]

Copied array: 
[[23 46 85]
 [43 56 99]
 [11 34 55]]


##### append element in array

In [51]:
# importing the module
import numpy as np

# creating an array
arr = np.array([1, 8, 3, 3, 5])
print('Original Array : ', arr)

# appending to the array
arr = np.append(arr, [7])
print('Array after appending : ', arr)


Original Array :  [1 8 3 3 5]
Array after appending :  [1 8 3 3 5 7]


In [52]:
# importing the module
import numpy as np

# creating an array
arr1 = np.array([1, 2, 3])
print('First array is : ', arr1)

# creating another array
arr2 = np.array([4, 5, 6])
print('Second array is : ', arr2)

# appending arr2 to arr1
arr = np.append(arr1, arr2)
print('Array after appending : ', arr)


First array is :  [1 2 3]
Second array is :  [4 5 6]
Array after appending :  [1 2 3 4 5 6]


In [53]:
# importing the module
import numpy as np

# create an array
arr = np.arange(1, 13).reshape(2, 6)
print('Original Array')
print(arr, '\n')

# create another array which is
# to be appended column-wise
col = np.arange(5, 11).reshape(1, 6)
print('Array to be appended column wise')
print(col)
arr_col = np.append(arr, col, axis = 0)
print('Array after appending the values column wise')
print(arr_col, '\n')

# create an array which is
# to be appended row wise
row = np.array([1, 2]).reshape(2, 1)
print('Array to be appended row wise')
print(row)
arr_row = np.append(arr, row, axis = 1)
print('Array after appending the values row wise')
print(arr_row)


Original Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

Array to be appended column wise
[[ 5  6  7  8  9 10]]
Array after appending the values column wise
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 5  6  7  8  9 10]] 

Array to be appended row wise
[[1]
 [2]]
Array after appending the values row wise
[[ 1  2  3  4  5  6  1]
 [ 7  8  9 10 11 12  2]]


###### Swapping the column of an array

In [54]:
# importing Module
import numpy as np


# creating array with shape(4,3)
my_array = np.arange(12).reshape(4, 3)
print("Original array:")
print(my_array)

# swapping the column with index of
# original array
my_array[:, [2, 0]] = my_array[:, [0, 2]]
print("After swapping arrays the last column and first column:")
print(my_array)


Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After swapping arrays the last column and first column:
[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


##### numpy.vstack() function is used to stack the sequence of input arrays vertically to make a single array.

In [55]:
# Python program explaining
# vstack() function

import numpy as geek

# input array
in_arr1 = geek.array([[ 1, 2, 3], [ -1, -2, -3]] )
print ("1st Input array : \n", in_arr1)

in_arr2 = geek.array([[ 4, 5, 6], [ -4, -5, -6]] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays vertically
out_arr = geek.vstack((in_arr1, in_arr2))
print ("Output stacked array :\n ", out_arr)


1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]
 [-4 -5 -6]]


In [56]:
# Python program explaining
# hstack() function

import numpy as geek

# input array
in_arr1 = geek.array([[ 1, 2, 3], [ -1, -2, -3]] )
print ("1st Input array : \n", in_arr1)

in_arr2 = geek.array([[ 4, 5, 6], [ -4, -5, -6]] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays horizontally
out_arr = geek.hstack((in_arr1, in_arr2))
print ("Output stacked array :\n ", out_arr)


1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3  4  5  6]
 [-1 -2 -3 -4 -5 -6]]


In [57]:
import numpy as np

block_1 = np.array([[1, 1], [1, 1]])
block_2 = np.array([[2, 2, 2], [2, 2, 2]])
block_3 = np.array([[3, 3], [3, 3], [3, 3]])
block_4 = np.array([[4, 4, 4], [4, 4, 4], [4, 4, 4]])

block_new = np.block([
	[block_1, block_2],
	[block_3, block_4]
])


print("the 1st block:\n",block_1)
print("the 2nd block:\n",block_2)
print("the 3rd block:\n",block_3)
print("the 4th block:\n",block_4)
print("the new block is :\n",block_new)


the 1st block:
 [[1 1]
 [1 1]]
the 2nd block:
 [[2 2 2]
 [2 2 2]]
the 3rd block:
 [[3 3]
 [3 3]
 [3 3]]
the 4th block:
 [[4 4 4]
 [4 4 4]
 [4 4 4]]
the new block is :
 [[1 1 2 2 2]
 [1 1 2 2 2]
 [3 3 4 4 4]
 [3 3 4 4 4]
 [3 3 4 4 4]]


In [58]:

import numpy as np


# 2-d array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print("array1 ")
print(arr1)

arr2 = np.array([0, 5, 10])
print("array2 ", arr2)

# print union of 2-d array and 1-d array
print("Union of two arrays", np.union1d(arr1, arr2))


array1 
[[1 2 3]
 [4 5 6]]
array2  [ 0  5 10]
Union of two arrays [ 0  1  2  3  4  5  6 10]


###### unique

In [59]:
import numpy as np

# Create a 2D numpy array
arr2D = np.array([[11, 11, 12, 11],
					[13, 11, 12, 11],
					[16, 11, 12, 11],
					[11, 11, 12, 11]])

print('Original Array :' ,
	arr2D, sep = '\n')

# Get unique rows from
# complete 2D-array by
# passing axis = 0 in
# unique function along
# with 2D-array
uniqueRows = np.unique(arr2D,
					axis = 0)

# print the output result
print('Unique Rows:',
	uniqueRows, sep = '\n')


Original Array :
[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]
 [11 11 12 11]]
Unique Rows:
[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]]


In [60]:
import numpy as np

a = [[10.2, 21.4, 3.6, 14.8], [1.0, 5.0, 10.0, 15.0]]

# using np.unique() method
ary = np.unique(a)

print(ary)


[ 1.   3.6  5.  10.  10.2 14.8 15.  21.4]


In [61]:
import numpy as geek
gfg = geek.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0))

# without trim parameter
# returns an array without any leading zeros

res = geek.trim_zeros(gfg, 'f')
# f for front
print(res)


[ 1  5  7  0  6  2  9  0 10  0  0]


In [62]:
import numpy as geek
gfg = geek.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0))

# without trim parameter
# returns an array without any trailing zeros

res = geek.trim_zeros(gfg, 'b')
# b for back

print(res)

[ 0  0  0  0  1  5  7  0  6  2  9  0 10]


###### filter 

In [63]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


######  Creating Filter Directly From Array

In [64]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


###### search

In [65]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

# Find the indexes where the value is 4:
x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [66]:
# Find the indexes where the values are even:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


##### Search Sorted

In [67]:
# Find the indexes where the value 7 should be inserted:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [68]:
# Find the indexes where the value 7 should be inserted, starting from the right:

import numpy as np

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [69]:
# Find the indexes where the values 2, 4, and 6 should be inserted:

import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


### Random array

In [70]:
# Generate a random integer from 0 to 100:

from numpy import random

x = random.randint(100)

print(x)

24


In [71]:
# Generate a random float from 0 to 1:

from numpy import random

x = random.rand()

print(x)

0.3916586547693858


In [72]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[81 43 19 83 49]
 [44  4 97 72 69]
 [36 61 67 73 49]]


In [73]:
# Return one of the values in an array:

from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

3


##### data distribution

In [74]:
# Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

# The probability for the value to be 3 is set to be 0.1

# The probability for the value to be 5 is set to be 0.3

# The probability for the value to be 7 is set to be 0.6

# The probability for the value to be 9 is set to be 0

from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 7 7 7 7 5 5 3 7 7 3 7 7 3 7 7 7 5 7 7 5 7 5 7 7 7 7 7 5 7 7 5 5 5 7 7 5
 3 5 5 5 5 3 5 7 5 7 7 5 7 5 7 5 7 7 5 5 5 3 3 7 5 7 5 7 7 7 7 7 5 3 7 5 7
 5 7 5 5 7 5 5 7 7 7 7 7 7 7 5 7 7 7 7 5 7 5 3 7 7 7]


In [75]:
# Same example as above, but return a 2-D array with 3 rows, each containing 5 values.

from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[7 7 7 7 5]
 [7 7 5 7 3]
 [7 7 7 7 7]]


In [76]:
a.T # returns the array, transposed
array([[3., 1., 7.],
[7., 4., 2.],
[3., 2., 4.],
[4., 2., 9.]])
a.T.shape

AttributeError: 'list' object has no attribute 'T'

## Matrix

###### operations on matrices

In [ ]:
# Python code to demonstrate matrix operations
# add(), subtract() and divide()

# importing numpy for matrix operations
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using add() to add matrices
print ("The element wise addition of matrix is : ")
print (numpy.add(x,y))

# using subtract() to subtract matrices
print ("The element wise subtraction of matrix is : ")
print (numpy.subtract(x,y))

# using divide() to divide matrices
print ("The element wise division of matrix is : ")
print (numpy.divide(x,y))


##### eigen values and eigen vectors 

In [8]:
import numpy as np

a = np.array([[3, 1], [2, 2]])
w, v = np.linalg.eig(a)

print("the eigen value is :\n",w)
print("the eigen vector is :\n",v)


# to verify using the equation
LHS=v[:,0] * w[0]
print("the lhs is:\n",LHS)

RHS=a @ v[:,0]
print("the rhs is\n",RHS)

# to check LHS RHS are equal
print(np.allclose(np.dot(a,v[:,0]),np.dot(w[0],v[:,0])))

the eigen value is :
 [4. 1.]
the eigen vector is :
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]
the lhs is:
 [2.82842712 2.82842712]
the rhs is
 [2.82842712 2.82842712]
True


##### example

In [11]:
import numpy as np
A =np.array([[1,1],[1.5,4.0]])
b =np.array([2200,5050])

np.linalg.solve(a,b)
print(x)


# alter
x = np.linalg.inv(A).dot(b)
print(x)

[1500.  700.]
